title: Lily Samoyan
description: Portfolio of an Engineer of all trades
logo : /img/headshot_circ.png
url: "https://lsamoy.github.io/lsamoyan"
social_links:
  linkedin: https://www.linkedin.com/lsamoyan
header_pages:
  - title: ML Enabled Buoys with Hydrophones
    url: /buoy/
include:
  - _pages

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
